[package]
name = "nft"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "nft"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
nft_integrity = { workspace = true } 
zome_utils = { workspace = true }
place_integrity = { workspace = true } 